In [1]:
# Dependencies
import pandas as pd
import numpy as np
import os

# Data Cleaning

In [2]:
# Path of the CSV file
csvfile = "gun_data_07_16.csv"

In [3]:
# Read CSV file into a pandas DataFrame
df = pd.read_csv(csvfile, dtype=object)
mortality_df = pd.read_csv("mortalitybystate.csv", dtype=object)

In [4]:
df = df.iloc[:,2:]

In [5]:
df = df.dropna(axis=0)
df.head()

,Month Code,County,County Code,Deaths,latitude,longitude
0,2007/01,"Maricopa County, AZ",4013,24,33.34883,-112.49123
1,2007/01,"Alameda County, CA",6001,11,37.6090291,-121.899142
2,2007/01,"Los Angeles County, CA",6037,64,34.3155072,-118.2096814
3,2007/01,"Sacramento County, CA",6067,12,38.4732259,-121.2980707
4,2007/01,"District of Columbia, DC",11001,14,38.8949549,-77.0366456

In [6]:
df[["County Code","Deaths"]] = df[["County Code","Deaths"]].astype(float).astype(int)

In [7]:
new_csv = "clean_gun_data_07_16.csv"
df.to_csv(new_csv, index=False)

# Database Creation

In [8]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy import create_engine, MetaData, inspect
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Numeric, Text, Float, Date
from sqlalchemy.orm import Session
import sqlite3

In [9]:
engine = create_engine("sqlite:///gun_data.sqlite")

In [10]:
# Create a connection to the engine called `conn`
conn = engine.connect()

In [11]:
Base = declarative_base()

class gunData(Base):
    __tablename__ = 'Mass_Shootings'

    id = Column(Integer, primary_key=True)
    month_code = Column(Text)
    county = Column(Text)
    county_code = Column(String)
    deaths = Column(String)
    latitude = Column(Float)
    longitude = Column(Float)

In [12]:
# Use `create_all` to create the shooting table in the database
Base.metadata.create_all(engine)

In [13]:
# Load the cleaned csv file into a pandas dataframe
new_df = pd.read_csv(new_csv)

In [14]:
session = Session(bind=engine)
conn = sqlite3.connect('gunData.sqlite')
cur = conn.cursor()

In [15]:
new_df.to_sql('Mass_Shootings',con=engine, index=False, if_exists="replace")
mortality_df.to_sql('mortalityState', con=engine, index=False, if_exists="replace")

In [16]:
session.commit()

In [17]:
engine.execute("select * from Mass_Shootings").fetchall()

[('2007/01', 'Maricopa County, AZ', 4013, 24, 33.34883, -112.49123),
 ('2007/01', 'Alameda County, CA', 6001, 11, 37.6090291, -121.899142),
 ('2007/01', 'Los Angeles County, CA', 6037, 64, 34.315507200000006, -118.20968140000001),
 ('2007/01', 'Sacramento County, CA', 6067, 12, 38.473225899999996, -121.2980707),
 ('2007/01', 'District of Columbia, DC', 11001, 14, 38.8949549, -77.03664559999999),
 ('2007/01', 'Duval County, FL', 12031, 14, 30.354007300000003, -81.66321090000001),
 ('2007/01', 'Miami-Dade County, FL', 12086, 20, 25.6364246, -80.4989467),
 ('2007/01', 'Cook County, IL', 17031, 21, 41.8197385, -87.756525),
 ('2007/01', 'Orleans Parish, LA', 22071, 12, 30.0801436, -89.93191340000001),
 ('2007/01', "Prince George's County, MD", 24033, 10, 38.803929, -76.85186949999999),
 ('2007/01', 'Baltimore city, MD', 24510, 19, 39.2559916, -76.634341),
 ('2007/01', 'Wayne County, MI', 26163, 23, 42.2682408, -83.28441720000001),
 ('2007/01', 'Clark County, NV', 32003, 13, 36.13440979, -115.0472645),
 ('2007/01', 'Essex County, NJ', 34013, 10, 40.791392200000004, -74.24794440000001),
 ('2007/01', 'Allegheny County, PA', 42003, 12, 40.459720399999995, -79.9760405),
 ('2007/01', 'Philadelphia County, PA', 42101, 28, 40.01145379999999, -75.1326504),
 ('2007/01', 'Shelby County, TN', 47157, 15, 35.1782557, -89.87397750000001),
 ('2007/01', 'Bexar County, TX', 48029, 12, 29.426398699999996, -98.5104781),
 ('2007/01', 'Dallas County, TX', 48113, 13, 32.762040500000005, -96.7790069),
 ('2007/01', 'Harris County, TX', 48201, 27, 29.811976899999998, -95.3741247),
 ('2007/02', 'Maricopa County, AZ', 4013, 26, 33.34883, -112.49123),
 ('2007/02', 'Los Angeles County, CA', 6037, 51, 34.315507200000006, -118.20968140000001),
 ('2007/02', 'Sacramento County, CA', 6067, 10, 38.473225899999996, -121.2980707),
 ('2007/02', 'San Bernardino County, CA', 6071, 11, 34.8253019, -116.0833144),
 ('2007/02', 'Miami-Dade County, FL', 12086, 17, 25.6364246, -80.4989467),
 ('2007/02', 'DeKalb County, GA', 13089, 10, 33.75756129999999, -84.21865079999999),
 ('2007/02', 'Cook County, IL', 17031, 24, 41.8197385, -87.756525),
 ('2007/02', 'Marion County, IN', 18097, 10, 39.781028899999995, -86.1365457),
 ('2007/02', 'Orleans Parish, LA', 22071, 11, 30.0801436, -89.93191340000001),
 ('2007/02', 'Baltimore city, MD', 24510, 14, 39.2559916, -76.634341),
 ('2007/02', 'Wayne County, MI', 26163, 19, 42.2682408, -83.28441720000001),
 ('2007/02', 'Clark County, NV', 32003, 11, 36.13440979, -115.0472645),
 ('2007/02', 'Allegheny County, PA', 42003, 10, 40.459720399999995, -79.9760405),
 ('2007/02', 'Philadelphia County, PA', 42101, 19, 40.01145379999999, -75.1326504),
 ('2007/02', 'Dallas County, TX', 48113, 16, 32.762040500000005, -96.7790069),
 ('2007/02', 'Harris County, TX', 48201, 20, 29.811976899999998, -95.3741247),
 ('2007/03', 'Maricopa County, AZ', 4013, 21, 33.34883, -112.49123),
 ('2007/03', 'Los Angeles County, CA', 6037, 51, 34.315507200000006, -118.20968140000001),
 ('2007/03', 'San Bernardino County, CA', 6071, 13, 34.8253019, -116.0833144),
 ('2007/03', 'District of Columbia, DC', 11001, 10, 38.8949549, -77.03664559999999),
 ('2007/03', 'Broward County, FL', 12011, 13, 26.1598074, -80.4623642),
 ('2007/03', 'Miami-Dade County, FL', 12086, 11, 25.6364246, -80.4989467),
 ('2007/03', 'Cook County, IL', 17031, 41, 41.8197385, -87.756525),
 ('2007/03', 'Orleans Parish, LA', 22071, 15, 30.0801436, -89.93191340000001),
 ('2007/03', "Prince George's County, MD", 24033, 14, 38.803929, -76.85186949999999),
 ('2007/03', 'Baltimore city, MD', 24510, 23, 39.2559916, -76.634341),
 ('2007/03', 'Wayne County, MI', 26163, 26, 42.2682408, -83.28441720000001),
 ('2007/03', 'Cuyahoga County, OH', 39035, 10, 41.4301347, -81.6905558),
 ('2007/03', 'Philadelphia County, PA', 42101, 36, 40.01145379999999, -75.1326504),
 ('2007/03', 'Shelby County, TN', 47157, 12, 35.1782557, -89.87397750000001),
 ('2007/03', 'Dallas County, TX', 48113, 22, 32.762040500000005, -96.7790069),
 ('2007/03', 'Harris County, TX', 48201, 31, 29.811976899999998, -95.3741247),
 ('2007/03', 'Milwaukee County, WI', 55079, 10, 43.01641545, -87.97373035),
 ('2007/04', 'Maricopa County, AZ', 4013, 21, 33.34883, -112.49123),
 ('2007/04', 'Los Angeles County, CA', 6037, 58, 34.315507200000006, -118.20968140000001),
 ('2007/04', 'San Bernardino County, CA', 6071, 16, 34.8253019, -116.0833144),
 ('2007/04', 'District of Columbia, DC', 11001, 10, 38.8949549, -77.03664559999999),
 ('2007/04', 'Miami-Dade County, FL', 12086, 23, 25.6364246, -80.4989467),
 ('2007/04', 'Fulton County, GA', 13121, 14, 34.0580391, -84.29612829999999),
 ('2007/04', 'Cook County, IL', 17031, 28, 41.8197385, -87.756525),
 ('2007/04', 'East Baton Rouge Parish, LA', 22033, 10, 30.5254797, -91.0899217),
 ('2007/04', "Prince George's County, MD", 24033, 13, 38.803929, -76.85186949999999),
 ('2007/04', 'Baltimore city, MD', 24510, 17, 39.2559916, -76.634341),
 ('2007/04', 'Wayne County, MI', 26163, 17, 42.2682408, -83.28441720000001),
 ('2007/04', 'Kings County, NY', 36047, 10, 40.64530975, -73.95502303),
 ('2007/04', 'Cuyahoga County, OH', 39035, 11, 41.4301347, -81.6905558),
 ('2007/04', 'Allegheny County, PA', 42003, 10, 40.459720399999995, -79.9760405),
 ('2007/04', 'Philadelphia County, PA', 42101, 34, 40.01145379999999, -75.1326504),
 ('2007/04', 'Shelby County, TN', 47157, 12, 35.1782557, -89.87397750000001),
 ('2007/04', 'Dallas County, TX', 48113, 14, 32.762040500000005, -96.7790069),
 ('2007/04', 'Harris County, TX', 48201, 23, 29.811976899999998, -95.3741247),
 ('2007/04', 'Montgomery County, VA', 51121, 10, 37.1810438, -80.3918782),
 ('2007/05', 'Maricopa County, AZ', 4013, 30, 33.34883, -112.49123),
 ('2007/05', 'Los Angeles County, CA', 6037, 66, 34.315507200000006, -118.20968140000001),
 ('2007/05', 'Riverside County, CA', 6065, 11, 33.721999100000005, -116.03724720000001),
 ('2007/05', 'San Diego County, CA', 6073, 12, 32.9637838, -116.7706277),
 ('2007/05', 'Duval County, FL', 12031, 10, 30.354007300000003, -81.66321090000001),
 ('2007/05', 'Miami-Dade County, FL', 12086, 15, 25.6364246, -80.4989467),
 ('2007/05', 'Orange County, FL', 12095, 17, 28.495156, -81.3111658),
 ('2007/05', 'Cook County, IL', 17031, 33, 41.8197385, -87.756525),
 ('2007/05', 'Lake County, IN', 18089, 12, 41.419382899999995, -87.36922270000001),
 ('2007/05', 'Orleans Parish, LA', 22071, 11, 30.0801436, -89.93191340000001),
 ('2007/05', 'Baltimore city, MD', 24510, 27, 39.2559916, -76.634341),
 ('2007/05', 'Wayne County, MI', 26163, 30, 42.2682408, -83.28441720000001),
 ('2007/05', 'Clark County, NV', 32003, 10, 36.13440979, -115.0472645),
 ('2007/05', 'Bronx County, NY', 36005, 11, 40.85703325, -73.83669616),
 ('2007/05', 'Kings County, NY', 36047, 22, 40.64530975, -73.95502303),
 ('2007/05', 'Cuyahoga County, OH', 39035, 17, 41.4301347, -81.6905558),
 ('2007/05', 'Philadelphia County, PA', 42101, 26, 40.01145379999999, -75.1326504),
 ('2007/05', 'Shelby County, TN', 47157, 13, 35.1782557, -89.87397750000001),
 ('2007/05', 'Dallas County, TX', 48113, 26, 32.762040500000005, -96.7790069),
 ('2007/05', 'Harris County, TX', 48201, 28, 29.811976899999998, -95.3741247),
 ('2007/06', 'Jefferson County, AL', 1073, 14, 33.5228184, -86.91645129999999),
 ('2007/06', 'Maricopa County, AZ', 4013, 20, 33.34883, -112.49123),
 ('2007/06', 'Alameda County, CA', 6001, 18, 37.6090291, -121.899142),
 ('2007/06', 'Los Angeles County, CA', 6037, 65, 34.315507200000006, -118.20968140000001),
 ('2007/06', 'San Bernardino County, CA', 6071, 22, 34.8253019, -116.0833144),
 ('2007/06', 'District of Columbia, DC', 11001, 20, 38.8949549, -77.03664559999999),
 ('2007/06', 'Broward County, FL', 12011, 11, 26.1598074, -80.4623642),
 ('2007/06', 'Duval County, FL', 12031, 11, 30.354007300000003, -81.66321090000001),
 ('2007/06', 'Miami-Dade County, FL', 12086, 17, 25.6364246, -80.4989467),
 ('2007/06', 'Fulton County, GA', 13121, 12, 34.0580391, -84.29612829999999),
 ('2007/06', 'Cook County, IL', 17031, 52, 41.8197385, -87.756525),
 ('2007/06', 'Orleans Parish, LA', 22071, 14, 30.0801436, -89.93191340000001),
 ('2007/06', 'Baltimore city, MD', 24510, 25, 39.2559916, -76.634341),
 ('2007/06', 'Wayne County, MI', 26163, 48, 42.2682408, -83.28441720000001),
 ('2007/06', 'Clark County, NV', 32003, 11, 36.13440979, -115.0472645),
 ('2007/06', 'Kings County, NY', 36047, 18, 40.64530975, -73.95502303),
 ('2007/06', 'Philadelphia County, PA', 42101, 31, 40.01145379999999, -75.1326504),
 ('2007/06', 'Shelby County, TN', 47157, 17, 35.1782557, -89.87397750000001),
 ('2007/06', 'Dallas County, TX', 48113, 14, 32.762040500000005, -96.7790069),
 ('2007/06', 'Harris County, TX', 48201, 17, 29.811976899999998, -95.3741247),
 ('2007/07', 'Jefferson County, AL', 1073, 18, 33.5228184, -86.91645129999999),
 ('2007/07', 'Maricopa County, AZ', 4013, 34, 33.34883, -112.49123),
 ('2007/07', 'Alameda County, CA', 6001, 13, 37.6090291, -121.899142),
 ('2007/07', 'Los Angeles County, CA', 6037, 81, 34.315507200000006, -118.20968140000001),
 ('2007/07', 'San Bernardino County, CA', 6071, 14, 34.8253019, -116.0833144),
 ('2007/07', 'San Diego County, CA', 6073, 10, 32.9637838, -116.7706277),
 ('2007/07', 'Duval County, FL', 12031, 16, 30.354007300000003, -81.66321090000001),
 ('2007/07', 'Miami-Dade County, FL', 12086, 17, 25.6364246, -80.4989467),
 ('2007/07', 'Orange County, FL', 12095, 11, 28.495156, -81.3111658),
 ('2007/07', 'Fulton County, GA', 13121, 17, 34.0580391, -84.29612829999999),
 ('2007/07', 'Cook County, IL', 17031, 36, 41.8197385, -87.756525),
 ('2007/07', 'Lake County, IN', 18089, 11, 41.419382899999995, -87.36922270000001),
 ('2007/07', 'Jefferson Parish, LA', 22051, 11, 29.8502657, -90.12938940000001),
 ('2007/07', 'Orleans Parish, LA', 22071, 14, 30.0801436, -89.93191340000001),
 ('2007/07', "Prince George's County, MD", 24033, 11, 38.803929, -76.85186949999999),
 ('2007/07', 'Baltimore city, MD', 24510, 19, 39.2559916, -76.634341),
 ('2007/07', 'Wayne County, MI', 26163, 30, 42.2682408, -83.28441720000001),
 ('2007/07', 'Clark County, NV', 32003, 16, 36.13440979, -115.0472645),
 ('2007/07', 'Kings County, NY', 36047, 20, 40.64530975, -73.95502303),
 ('2007/07', 'Cuyahoga County, OH', 39035, 18, 41.4301347, -81.6905558),
 ('2007/07', 'Philadelphia County, PA', 42101, 34, 40.01145379999999, -75.1326504),
 ('2007/07', 'Shelby County, TN', 47157, 17, 35.1782557, -89.87397750000001),
 ('2007/07', 'Bexar County, TX', 48029, 10, 29.426398699999996, -98.5104781),
 ('2007/07', 'Dallas County, TX', 48113, 13, 32.762040500000005, -96.7790069),
 ('2007/07', 'Harris County, TX', 48201, 33, 29.811976899999998, -95.3741247),
 ('2007/07', 'Milwaukee County, WI', 55079, 10, 43.01641545, -87.97373035),
 ('2007/08', 'Maricopa County, AZ', 4013, 20, 33.34883, -112.49123),
 ('2007/08', 'Alameda County, CA', 6001, 11, 37.6090291, -121.899142),
 ('2007/08', 'Fresno County, CA', 6019, 11, 36.671350200000006, -119.8155355),
 ('2007/08', 'Los Angeles County, CA', 6037, 73, 34.315507200000006, -118.20968140000001),
 ('2007/08', 'San Bernardino County, CA', 6071, 13, 34.8253019, -116.0833144),
 ('2007/08', 'District of Columbia, DC', 11001, 10, 38.8949549, -77.03664559999999),
 ('2007/08', 'Duval County, FL', 12031, 12, 30.354007300000003, -81.66321090000001),
 ('2007/08', 'Miami-Dade County, FL', 12086, 15, 25.6364246, -80.4989467),
 ('2007/08', 'DeKalb County, GA', 13089, 10, 33.75756129999999, -84.21865079999999),
 ('2007/08', 'Fulton County, GA', 13121, 13, 34.0580391, -84.29612829999999),
 ('2007/08', 'Cook County, IL', 17031, 50, 41.8197385, -87.756525),
 ('2007/08', 'Jefferson County, KY', 21111, 11, 38.1787175, -85.664528),
 ('2007/08', 'Orleans Parish, LA', 22071, 25, 30.0801436, -89.93191340000001),
 ('2007/08', "Prince George's County, MD", 24033, 12, 38.803929, -76.85186949999999),
 ('2007/08', 'Baltimore city, MD', 24510, 28, 39.2559916, -76.634341),
 ('2007/08', 'Wayne County, MI', 26163, 37, 42.2682408, -83.28441720000001),
 ('2007/08', 'Clark County, NV', 32003, 12, 36.13440979, -115.0472645),
 ('2007/08', 'Bronx County, NY', 36005, 12, 40.85703325, -73.83669616),
 ('2007/08', 'Hamilton County, OH', 39061, 11, 39.2085354, -84.55018740000001),
 ('2007/08', 'Philadelphia County, PA', 42101, 23, 40.01145379999999, -75.1326504),
 ('2007/08', 'Bexar County, TX', 48029, 10, 29.426398699999996, -98.5104781),
 ('2007/08', 'Dallas County, TX', 48113, 14, 32.762040500000005, -96.7790069),
 ('2007/08', 'Harris County, TX', 48201, 31, 29.811976899999998, -95.3741247),
 ('2007/09', 'Jefferson County, AL', 1073, 10, 33.5228184, -86.91645129999999),
 ('2007/09', 'Maricopa County, AZ', 4013, 18, 33.34883, -112.49123),
 ('2007/09', 'Alameda County, CA', 6001, 17, 37.6090291, -121.899142),
 ('2007/09', 'Los Angeles County, CA', 6037, 56, 34.315507200000006, -118.20968140000001),
 ('2007/09', 'District of Columbia, DC', 11001, 14, 38.8949549, -77.03664559999999),
 ('2007/09', 'Miami-Dade County, FL', 12086, 12, 25.6364246, -80.4989467),
 ('2007/09', 'DeKalb County, GA', 13089, 10, 33.75756129999999, -84.21865079999999),
 ('2007/09', 'Fulton County, GA', 13121, 12, 34.0580391, -84.29612829999999),
 ('2007/09', 'Cook County, IL', 17031, 47, 41.8197385, -87.756525),
 ('2007/09', 'East Baton Rouge Parish, LA', 22033, 10, 30.5254797, -91.0899217),
 ('2007/09', 'Orleans Parish, LA', 22071, 14, 30.0801436, -89.93191340000001),
 ('2007/09', 'Baltimore city, MD', 24510, 15, 39.2559916, -76.634341),
 ('2007/09', 'Wayne County, MI', 26163, 43, 42.2682408, -83.28441720000001),
 ('2007/09', 'Jackson County, MO', 29095, 11, 40.6531945, -106.3447246),
 ('2007/09', 'Essex County, NJ', 34013, 12, 40.791392200000004, -74.24794440000001),
 ('2007/09', 'Kings County, NY', 36047, 15, 40.64530975, -73.95502303),
 ('2007/09', 'Philadelphia County, PA', 42101, 20, 40.01145379999999, -75.1326504),
 ('2007/09', 'Bexar County, TX', 48029, 10, 29.426398699999996, -98.5104781),
 ('2007/09', 'Dallas County, TX', 48113, 18, 32.762040500000005, -96.7790069),
 ('2007/09', 'Harris County, TX', 48201, 23, 29.811976899999998, -95.3741247),
 ('2007/09', 'Milwaukee County, WI', 55079, 13, 43.01641545, -87.97373035),
 ('2007/10', 'Jefferson County, AL', 1073, 12, 33.5228184, -86.91645129999999),
 ('2007/10', 'Maricopa County, AZ', 4013, 21, 33.34883, -112.49123),
 ('2007/10', 'Contra Costa County, CA', 6013, 10, 37.9034806, -121.9175345),
 ('2007/10', 'Los Angeles County, CA', 6037, 59, 34.315507200000006, -118.20968140000001),
 ('2007/10', 'District of Columbia, DC', 11001, 16, 38.8949549, -77.03664559999999),
 ('2007/10', 'Duval County, FL', 12031, 13, 30.354007300000003, -81.66321090000001),
 ('2007/10', 'Miami-Dade County, FL', 12086, 14, 25.6364246, -80.4989467),
 ('2007/10', 'Cook County, IL', 17031, 38, 41.8197385, -87.756525),
 ('2007/10', 'Orleans Parish, LA', 22071, 22, 30.0801436, -89.93191340000001),
 ('2007/10', 'Baltimore city, MD', 24510, 16, 39.2559916, -76.634341),
 ('2007/10', 'Wayne County, MI', 26163, 37, 42.2682408, -83.28441720000001),
 ('2007/10', 'Essex County, NJ', 34013, 11, 40.791392200000004, -74.24794440000001),
 ('2007/10', 'Bronx County, NY', 36005, 10, 40.85703325, -73.83669616),
 ('2007/10', 'Kings County, NY', 36047, 14, 40.64530975, -73.95502303),
 ('2007/10', 'Philadelphia County, PA', 42101, 30, 40.01145379999999, -75.1326504),
 ('2007/10', 'Shelby County, TN', 47157, 13, 35.1782557, -89.87397750000001),
 ('2007/10', 'Dallas County, TX', 48113, 20, 32.762040500000005, -96.7790069),
 ('2007/10', 'Harris County, TX', 48201, 27, 29.811976899999998, -95.3741247),
 ('2007/10', 'Tarrant County, TX', 48439, 10, 32.7513658, -97.335696),
 ('2007/10', 'Milwaukee County, WI', 55079, 14, 43.01641545, -87.97373035),
 ('2007/11', 'Jefferson County, AL', 1073, 12, 33.5228184, -86.91645129999999),
 ('2007/11', 'Maricopa County, AZ', 4013, 30, 33.34883, -112.49123),
 ('2007/11', 'Los Angeles County, CA', 6037, 48, 34.315507200000006, -118.20968140000001),
 ('2007/11', 'District of Columbia, DC', 11001, 10, 38.8949549, -77.03664559999999),
 ('2007/11', 'Broward County, FL', 12011, 12, 26.1598074, -80.4623642),
 ('2007/11', 'Duval County, FL', 12031, 11, 30.354007300000003, -81.66321090000001),
 ('2007/11', 'Miami-Dade County, FL', 12086, 21, 25.6364246, -80.4989467),
 ('2007/11', 'Palm Beach County, FL', 12099, 10, 26.627979800000002, -80.44941740000002),
 ('2007/11', 'DeKalb County, GA', 13089, 11, 33.75756129999999, -84.21865079999999),
 ('2007/11', 'Fulton County, GA', 13121, 12, 34.0580391, -84.29612829999999),
 ('2007/11', 'Cook County, IL', 17031, 30, 41.8197385, -87.756525),
 ('2007/11', 'Orleans Parish, LA', 22071, 12, 30.0801436, -89.93191340000001),
 ('2007/11', "Prince George's County, MD", 24033, 11, 38.803929, -76.85186949999999),
 ('2007/11', 'Baltimore city, MD', 24510, 12, 39.2559916, -76.634341),
 ('2007/11', 'Wayne County, MI', 26163, 23, 42.2682408, -83.28441720000001),
 ('2007/11', 'St. Louis city, MO', 29510, 14, 38.626793799999994, -90.19770345),
 ('2007/11', 'Clark County, NV', 32003, 10, 36.13440979, -115.0472645),
 ('2007/11', 'Essex County, NJ', 34013, 12, 40.791392200000004, -74.24794440000001),
 ('2007/11', 'Kings County, NY', 36047, 16, 40.64530975, -73.95502303),
 ('2007/11', 'Philadelphia County, PA', 42101, 27, 40.01145379999999, -75.1326504),
 ('2007/11', 'Dallas County, TX', 48113, 15, 32.762040500000005, -96.7790069),
 ('2007/11', 'Harris County, TX', 48201, 26, 29.811976899999998, -95.3741247),
 ('2007/12', 'Maricopa County, AZ', 4013, 12, 33.34883, -112.49123),
 ('2007/12', 'Alameda County, CA', 6001, 16, 37.6090291, -121.899142),
 ('2007/12', 'Contra Costa County, CA', 6013, 19, 37.9034806, -121.9175345),
 ('2007/12', 'Los Angeles County, CA', 6037, 49, 34.315507200000006, -118.20968140000001),
 ('2007/12', 'San Bernardino County, CA', 6071, 12, 34.8253019, -116.0833144),
 ('2007/12', 'Miami-Dade County, FL', 12086, 22, 25.6364246, -80.4989467),
 ('2007/12', 'Cook County, IL', 17031, 27, 41.8197385, -87.756525),
 ('2007/12', 'Marion County, IN', 18097, 14, 39.781028899999995, -86.1365457),
 ('2007/12', 'Orleans Parish, LA', 22071, 13, 30.0801436, -89.93191340000001),
 ('2007/12', 'Baltimore city, MD', 24510, 10, 39.2559916, -76.634341),
 ('2007/12', 'Wayne County, MI', 26163, 20, 42.2682408, -83.28441720000001),
 ('2007/12', 'St. Louis city, MO', 29510, 11, 38.626793799999994, -90.19770345),
 ('2007/12', 'Essex County, NJ', 34013, 12, 40.791392200000004, -74.24794440000001),
 ('2007/12', 'Kings County, NY', 36047, 21, 40.64530975, -73.95502303),
 ('2007/12', 'Mecklenburg County, NC', 37119, 14, 35.2356385, -80.8139485),
 ('2007/12', 'Philadelphia County, PA', 42101, 16, 40.01145379999999, -75.1326504),
 ('2007/12', 'Shelby County, TN', 47157, 13, 35.1782557, -89.87397750000001),
 ('2007/12', 'Dallas County, TX', 48113, 16, 32.762040500000005, -96.7790069),
 ('2007/12', 'Harris County, TX', 48201, 30, 29.811976899999998, -95.3741247),
 ('2008/01', 'Jefferson County, AL', 1073, 10, 33.5228184, -86.91645129999999),
 ('2008/01', 'Maricopa County, AZ', 4013, 21, 33.34883, -112.49123),
 ('2008/01', 'Los Angeles County, CA', 6037, 60, 34.315507200000006, -118.20968140000001),
 ('2008/01', 'San Bernardino County, CA', 6071, 15, 34.8253019, -116.0833144),
 ('2008/01', 'Duval County, FL', 12031, 11, 30.354007300000003, -81.66321090000001),
 ('2008/01', 'Miami-Dade County, FL', 12086, 17, 25.6364246, -80.4989467),
 ('2008/01', 'Cook County, IL', 17031, 30, 41.8197385, -87.756525),
 ('2008/01', 'Marion County, IN', 18097, 12, 39.781028899999995, -86.1365457),
 ('2008/01', 'Orleans Parish, LA', 22071, 11, 30.0801436, -89.93191340000001),
 ('2008/01', 'Baltimore city, MD', 24510, 14, 39.2559916, -76.634341),
 ('2008/01', 'Wayne County, MI', 26163, 23, 42.2682408, -83.28441720000001),
 ('2008/01', 'Allegheny County, PA', 42003, 10, 40.459720399999995, -79.9760405),
 ('2008/01', 'Philadelphia County, PA', 42101, 20, 40.01145379999999, -75.1326504),

In [18]:
pd.read_sql('Mass_Shootings', con=engine)

,Month Code,County,County Code,Deaths,latitude,longitude
0,2007/01,"Maricopa County, AZ",4013,24,33.348830,-112.491230
1,2007/01,"Alameda County, CA",6001,11,37.609029,-121.899142
2,2007/01,"Los Angeles County, CA",6037,64,34.315507,-118.209681
3,2007/01,"Sacramento County, CA",6067,12,38.473226,-121.298071
4,2007/01,"District of Columbia, DC",11001,14,38.894955,-77.036646
5,2007/01,"Duval County, FL",12031,14,30.354007,-81.663211
6,2007/01,"Miami-Dade County, FL",12086,20,25.636425,-80.498947
7,2007/01,"Cook County, IL",17031,21,41.819738,-87.756525
8,2007/01,"Orleans Parish, LA",22071,12,30.080144,-89.931913
9,2007/01,"Prince George's County, MD",24033,10,38.803929,-76.851869
10,2007/01,"Baltimore city, MD",24510,19,39.255992,-76.634341
11,2007/01,"Wayne County, MI",26163,23,42.268241,-83.284417
12,2007/01,"Clark County, NV",32003,13,36.134410,-115.047264
13,2007/01,"Essex County, NJ",34013,10,40.791392,-74.247944
14,2007/01,"Allegheny County, PA",42003,12,40.459720,-79.976040
15,2007/01,"Philadelphia County, PA",42101,28,40.011454,-75.132650
16,2007/01,"Shelby County, TN",47157,15,35.178256,-89.873978
17,2007/01,"Bexar County, TX",48029,12,29.426399,-98.510478
18,2007/01,"Dallas County, TX",48113,13,32.762041,-96.779007
19,2007/01,"Harris County, TX",48201,27,29.811977,-95.374125
20,2007/02,"Maricopa County, AZ",4013,26,33.348830,-112.491230
21,2007/02,"Los Angeles County, CA",6037,51,34.315507,-118.209681
22,2007/02,"Sacramento County, CA",6067,10,38.473226,-121.298071
23,2007/02,"San Bernardino County, CA",6071,11,34.825302,-116.083314
24,2007/02,"Miami-Dade County, FL",12086,17,25.636425,-80.498947
25,2007/02,"DeKalb County, GA",13089,10,33.757561,-84.218651
26,2007/02,"Cook County, IL",17031,24,41.819738,-87.756525
27,2007/02,"Marion County, IN",18097,10,39.781029,-86.136546
28,2007/02,"Orleans Parish, LA",22071,11,30.080144,-89.931913
29,2007/02,"Baltimore city, MD",24510,14,39.255992,-76.634341
...,...,...,...,...,...,...
2092,2016/11,"Philadelphia County, PA",42101,18,40.011454,-75.132650
2093,2016/11,"Shelby County, TN",47157,12,35.178256,-89.873978
2094,2016/11,"Bexar County, TX",48029,12,29.426399,-98.510478
2095,2016/11,"Dallas County, TX",48113,10,32.762041,-96.779007
2096,2016/11,"Harris County, TX",48201,23,29.811977,-95.374125
2097,2016/12,"Jefferson County, AL",1073,11,33.522818,-86.916451
2098,2016/12,"Maricopa County, AZ",4013,12,33.348830,-112.491230
2099,2016/12,"Alameda County, CA",6001,12,37.609029,-121.899142
2100,2016/12,"Los Angeles County, CA",6037,30,34.315507,-118.209681
2101,2016/12,"Broward County, FL",12011,10,26.159807,-80.462364
2102,2016/12,"Miami-Dade County, FL",12086,11,25.636425,-80.498947
2103,2016/12,"Palm Beach County, FL",12099,10,26.627980,-80.449417
2104,2016/12,"Fulton County, GA",13121,11,34.058039,-84.296128
2105,2016/12,"Cook County, IL",17031,59,41.819738,-87.756525
2106,2016/12,"Marion County, IN",18097,12,39.781029,-86.136546
2107,2016/12,"Jefferson County, KY",21111,10,38.178717,-85.664528
2108,2016/12,"Orleans Parish, LA",22071,12,30.080144,-89.931913
2109,2016/12,"Prince George's County, MD",24033,10,38.803929,-76.851869
2110,2016/12,"Baltimore city, MD",24510,24,39.255992,-76.634341
2111,2016/12,"Wayne County, MI",26163,24,42.268241,-83.284417
2112,2016/12,"Jackson County, MO",29095,13,40.653194,-106.344725
2113,2016/12,"St. Louis city, MO",29510,13,38.626794,-90.197703
2114,2016/12,"Cuyahoga County, OH",39035,14,41.430135,-81.690556
2115,2016/12,"Franklin County, OH",39049,13,40.028316,-83.007666
2116,2016/12,"Philadelphia County, PA",42101,16,40.011454,-75.132650
2117,2016/12,"Davidson County, TN",47037,13,36.189724,-86.785786
2118,2016/12,"Shelby County, TN",47157,20,35.178256,-89.873978
2119,2016/12,"Bexar County, TX",48029,12,29.426399,-98.510478
2120,2016/12,"Harris County, TX",48201,34,29.811977,-95.374125
2121,2016/12,"Milwaukee County, WI",55079,16,43.016415,-87.973730

In [19]:
from flask import Flask, render_template, jsonify

app = Flask(__name__)

@app.route("/")
def index(): 
    return render_template ("index.html")

@app.route('/gunData')
def metadata(): 
    record = pd.read_sql('Mass_Shootings', con=engine).to_dict("records")
    return jsonify(record)

@app.route('/mortalityState')
def mortality(): 
    record = pd.read_sql('mortalityState', con=engine).to_dict("records")
    return jsonify(record)

@app.route('/timePeriod')
def timeSeries(): 
    record = pd.read_sql('''select "Month Code" from Mass_Shootings''', con=engine).to_dict("records")
    return jsonify(record)

if __name__ == '__main__':
    app.run(host="127.0.0.1", port=5000, debug=True)

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat

SystemExit: 1

/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)